/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * 
 */
export interface AclListResponse { 
    status_code: 200;
    result: 'OK';
    permissions: Array<AclPermissionItem>;
}






/**
 * 
 */
export interface AclPermissionItem { 
    role_id: string;
    role_name: string;
    allowed_actions: Array<string>;
    allowed_pages: Array<string>;
}




export interface ErrorMessage403 {
  status_code: 403;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * 
 */
export interface AclActionRequest { 
    role_id: string;
    action: string;
}






/**
 * 
 */
export interface AclJobResponse { 
    status_code: 200;
    result: 'OK';
    job_id: string;
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage409 {
  status_code: 409;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * 
 */
export interface AclPageRequest { 
    role_id: string;
    page: string;
}

