/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Request body for user login.
 */
export interface AuthLoginRequest { 
    /**
     * id of the user, used for admin and leader login
     */
    user_id?: string;
    /**
     * Role of the user (admin, leader, staff)
     */
    role: string;
    /**
     * Plain text password for the user (will be hashed)
     */
    password: string;
    /**
     * Short code of the branch, used for staff login
     */
    branch_code?: string;
    /**
     * Short code of the hospital, used for staff login
     */
    hospital_code?: string;
    /**
     * Browser UUID from localStorage for device tracking
     */
    device_id?: string;
    /**
     * Client IP address
     */
    ip_address?: string;
    /**
     * Browser User-Agent string
     */
    user_agent?: string;
}






/**
 * Response body returned after a successful user login.
 */
export interface AuthLoginResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * The role of the user who logged in (管理者 | リーダー | スタッフ)
     */
    role: string;
    /**
     * The role of the user who logged in (管理者 | リーダー | スタッフ)
     */
    user_name: string;
    /**
     * The ID the user logged in with
     */
    login_id?: string;
    /**
     * The branch name if the logged in user is a leader
     */
    branch_name?: string;
    permission: AuthLoginResponsePermission;
}






/**
 * Permission information returned upon successful login.
 */
export interface AuthLoginResponsePermission { 
    /**
     * id of the role permission
     */
    role_id: string;
    /**
     * name of the role
     */
    role_name: string;
    /**
     * list of actions that are allowed to perform by this user
     */
    allowed_actions: Array<string>;
    /**
     * list of pages that are allowed to be seen by this user
     */
    allowed_pages: Array<string>;
}




export interface ErrorMessage401 {
  status_code: 401;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for logging out a user.
 */
export interface AuthLogoutRequest { 
    /**
     * player id of the user
     */
    player_id?: string;
}






/**
 * Response body returned after a successful user logout.
 */
export interface AuthLogoutResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * logout success message
     */
    message: string;
}




/**
 * Response returned with role and permissions information of the specified user.
 */
export interface AuthWhoAmIResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the role permission
     */
    role_id: string;
    /**
     * name of the role
     */
    role_name: string;
    /**
     * list of actions that are allowed to perform by this user
     */
    allowed_actions: Array<string>;
    /**
     * list of pages that are allowed to be seen by this user
     */
    allowed_pages: Array<string>;
    /**
     * display name of the user
     */
    full_name: string;
    /**
     * The ID the user logged in with
     */
    login_id?: string;
    /**
     * UUID of the hospital (nk staff and hospital staff only)
     */
    hospital_id?: string;
    /**
     * Short code identifying the hospital (nk staff and hospital staff only)
     */
    hospital_code?: string;
    /**
     * UUID of the branch (leader, nk staff, and hospital staff only)
     */
    branch_id?: string;
    /**
     * Short code identifying the branch (leader, nk staff, and hospital staff only)
     */
    branch_code?: string;
    /**
     * True when this session is scoped to the demo schema
     */
    is_demo: boolean;
}

