/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after a successful user login.
 */
export interface BranchListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * Id of newly created user
     */
    branch_list: Array<BranchListResponseBranch>;
}






/**
 * Branch information returned upon successful login.
 */
export interface BranchListResponseBranch { 
    /**
     * Unique primary key of the branch
     */
    id: string;
    /**
     * User defined ID of the branch
     */
    branch_id: string;
    /**
     * Short code for the branch
     */
    branch_code: string;
    /**
     * Branch name
     */
    branch_name: string;
}




export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for user password reset.
 */
export interface CreateBranchRequest { 
    /**
     * Unique short code for the branch (4-8 characters)
     */
    branch_code: string;
    /**
     * ID of the branch
     */
    branch_id: string;
    /**
     * Name of the branch
     */
    branch_name: string;
}






/**
 * Response body returned after a successful user password reset.
 */
export interface CreateBranchResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the user that has been created
     */
    branch_id: string;
    /**
     * id of the job that is creating the user and notify uid
     */
    job_id: string;
}




/**
 * Request body of branch update
 */
export interface BranchUpdateRequest { 
    /**
     * Partition key of the branch
     */
    id: string;
    /**
     * Short code for the branch
     */
    branch_code: string;
    /**
     * Required Branch ID
     */
    branch_id: string;
    /**
     * New name of the branch
     */
    branch_name?: string;
}






/**
 * Response body returned after successfully updating branch.
 */
export interface BranchUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Branch update api response
     */
    message: string;
    /**
     * id of the job that is creating the branch and notify uid
     */
    job_id: string;
}

