/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * 
 */
export interface DataClearRequest { 
    /**
     * Name of the table to clear
     */
    table_name: string;
    /**
     * ID of the specific record to delete. Required when all_clear is False.
     */
    id?: string;
    /**
     * True to delete every row in the table; False to delete only the row with the given id.
     */
    all_clear: boolean;
}






/**
 * 
 */
export interface DataClearResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Table that was targeted
     */
    table_name: string;
    /**
     * Number of rows deleted
     */
    deleted_count: number;
}





export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage401 {
  status_code: 401;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}

