/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after retrieving delivery request details.
 */
export interface DeliveryRequestDetailsResponse { 
    status_code: 200;
    result: 'OK';
    delivery_request: DeliveryRequestDetailsInfo;
}






/**
 * Full detail of a single delivery request (supports both ADMIN_STAFF and HOSPITAL_STAFF)
 */
export interface DeliveryRequestDetailsInfo { 
    /**
     * ID of the delivery list (delivery_lists.id)
     */
    request_id: string;
    /**
     * \'2\' (ADMIN_STAFF) or \'3\' (HOSPITAL_STAFF)
     */
    user_type: string;
    /**
     * Room ID; populated for ADMIN_STAFF delivery lists
     */
    room_id?: string;
    /**
     * Room number ID; populated for ADMIN_STAFF delivery lists
     */
    room_number_id?: string;
    /**
     * Classification ID; populated for HOSPITAL_STAFF delivery lists
     */
    classification_id?: string;
    /**
     * Classification room ID; populated for HOSPITAL_STAFF delivery lists
     */
    classification_room_id?: string;
    /**
     * Classification name; populated for HOSPITAL_STAFF delivery lists
     */
    classification_name?: string;
    /**
     * Classification room number; populated for HOSPITAL_STAFF delivery lists
     */
    classification_room_number?: string;
    /**
     * Patient identifier
     */
    patient_id?: string;
    /**
     * Patient surname
     */
    patient_surname: string;
    /**
     * Patient given name
     */
    patient_name: string;
    /**
     * Patient kana surname
     */
    kana_surname: string;
    /**
     * Patient kana given name
     */
    kana_name: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    suburb?: string;
    remaining_address?: string;
    home_phone_number?: string;
    cell_phone_number?: string;
    /**
     * Additional notes for the delivery request
     */
    notes?: string;
    /**
     * Billing contact for this delivery request, if one has been registered
     */
    delivery_billing?: CreateDeliveryBillingResponseInfo | null;
    /**
     * Services associated with this delivery request
     */
    services: Array<ServiceDetailInfo>;
    /**
     * Options associated with this delivery request
     */
    options: Array<OptionDetailInfo>;
    /**
     * Last updated timestamp (ISO 8601)
     */
    updated_at: string;
}





/**
 * Option detail with delivery date, price and quantity
 */
export interface OptionDetailInfo {
    /**
     * delivery_list_options.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable options.option_id from the master record. Null for legacy records.
     */
    option_id?: string;
    /**
     * Master options.id UUID (delivery_list_options.source_option_id). Null for legacy records.
     */
    master_option_id?: string;
    /**
     * Delivery date for this option (YYYY-MM-DD)
     */
    option_delivery_date: string;
    /**
     * Name of the option
     */
    option_name: string;
    /**
     * Daily price of the option
     */
    daily_price: number;
    /**
     * Quantity of this option
     */
    quantity: number;
}





/**
 * Service detail with date range and its sets
 */
export interface ServiceDetailInfo {
    /**
     * delivery_list_services.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable services.service_id from the master record. Null for legacy records.
     */
    service_id?: string;
    /**
     * Master services.id UUID (delivery_list_services.source_service_id). Null for legacy records.
     */
    master_service_id?: string;
    /**
     * Name of the service
     */
    service_name: string;
    /**
     * Daily price of the service
     */
    daily_price: number;
    /**
     * Service start date (YYYY-MM-DD)
     */
    start_date: string;
    /**
     * Service end date (YYYY-MM-DD); null when open-ended
     */
    end_date?: string;
    /**
     * Sets belonging to this service
     */
    sub_services: Array<SubServiceDetailInfo>;
}





/**
 * Sub-service set detail within a service
 */
export interface SubServiceDetailInfo {
    /**
     * delivery_list_service_sets.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable sets.set_id, denormalized onto delivery_list_service_sets.set_id
     */
    set_id: string;
    /**
     * Master sets.id UUID (delivery_list_service_sets.source_set_id). Null for legacy records.
     */
    master_set_id?: string;
    /**
     * Name of the sub-service set
     */
    set_name: string;
    /**
     * Size of the sub-service set
     */
    size: string;
}




export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Response body returned after a successful delivery request list retrieval.
 */
export interface DeliveryRequestListForStaffResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * List of delivery requests
     */
    delivery_request_list: Array<DeliveryRequestListForStaffResponseInfo>;
}






/**
 * Delivery request information returned in the delivery request list response.
 */
export interface DeliveryRequestListForStaffResponseInfo { 
    /**
     * ID of the hospital
     */
    request_id: string;
    /**
     * Whether the logged-in hospital's 配達/配達なし action buttons should be shown
     */
    show_delivery_button?: boolean;
    /**
     * Which location chain this record uses: 'ADMIN_STAFF' (room) or
     * 'HOSPITAL_STAFF' (classification room)
     */
    user_type?: string;
    /**
     * rooms.id associated with the delivery. Null on HOSPITAL_STAFF records.
     */
    room_id?: string | null;
    /**
     * 部屋番号 — the room's number on ADMIN_STAFF records, the classification
     * room's number on HOSPITAL_STAFF ones
     */
    room_number: string;
    room: DeliveryRequestListForStaffRoom;
    /**
     * hospital_classifications.id. HOSPITAL_STAFF records only.
     */
    classification_id?: string | null;
    /**
     * classification_rooms.id. HOSPITAL_STAFF records only.
     */
    classification_room_id?: string | null;
    /**
     * 区分 — name of the classification. HOSPITAL_STAFF records only.
     */
    classification_name?: string | null;
    /**
     * 部屋番号 of the classification room. HOSPITAL_STAFF records only.
     */
    classification_room_number?: string | null;
    /**
     * 配達停止期間 of the delivery list. HOSPITAL_STAFF records only, and null on
     * one that has no window recorded.
     */
    suspension_period?: DeliveryRequestListForStaffSuspensionPeriod | null;
    /**
     * list of deliveries associated with this delivery requests
     */
    delivery_lists: Array<DeliveryRequestListResponseDeliveryList>;
    /**
     * Patient identifier
     */
    patient_id?: string;
    /**
     * Name of the patient
     */
    patient_name: string;
    /**
     * Kana name of the patient
     */
    kana_name: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    suburb?: string;
    remaining_address?: string;
    home_phone_number?: string;
    cell_phone_number?: string;
    /**
     * List of Service IDs with date ranges associated with the delivery request
     */
    service_ids: Array<DeliveryRequestForStaffServiceIdModel>;
    /**
     * List of Option IDs with date ranges associated with the delivery request
     */
    options: Array<DeliveryRequestForStaffOptionIdModel>;
    /**
     * delivery date of the option (option_delivery_date)
     */
    option_date?: string;
    /**
     * Additional notes for the delivery request
     */
    notes?: string;
}





/**
 * Suspension period (配達停止期間) associated with a HOSPITAL_STAFF delivery list.
 */
export interface DeliveryRequestListForStaffSuspensionPeriod {
    /**
     * Suspension start date (YYYY-MM-DD)
     */
    suspension_start_date: string;
    /**
     * Suspension end date (YYYY-MM-DD)
     */
    suspension_end_date: string;
}


/**
 * Room information associated with the delivery request
 */
export interface DeliveryRequestListForStaffRoom {
    /**
     * id of the room
     */
    room_id: string;
    /**
     * Floor name (e.g., 1階)
     */
    floor_number: string;
    /**
     * Route name (e.g., A-ルート)
     */
    route_name: string;
    /**
     * Building name (e.g., 西)
     */
    building_name: string;
    /**
     * Room numbers (e.g., [\'101\', \'201\'])
     */
    room_number: Array<string>;
}





/**
 * Option with quantity
 */
export interface DeliveryRequestForStaffOptionIdModel {
    /**
     * delivery_list_options.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable options.option_id from the master record. Null for legacy records.
     */
    option_id?: string;
    /**
     * Master options.id UUID (delivery_list_options.source_option_id). Null for legacy records.
     */
    master_option_id?: string;
    /**
     * Option name
     */
    option_name?: string;
    /**
     * Quantity of the option
     */
    quantity: number;
    /**
     * Daily price of the option (delivery_list_option_data.daily_price).
     */
    option_price?: number;
}





/**
 * Service with date range and sub-services
 */
export interface DeliveryRequestForStaffServiceIdModel {
    /**
     * delivery_list_services.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable services.service_id from the master record. Null for legacy records.
     */
    service_id?: string;
    /**
     * Master services.id UUID (delivery_list_services.source_service_id). Null for legacy records.
     */
    master_service_id?: string;
    /**
     * Service start date
     */
    start_date: string;
    /**
     * Service end date
     */
    end_date: string;
    /**
     * Service name
     */
    service_name?: string;
    /**
     * Daily price of the service (delivery_list_services.daily_price).
     */
    service_price?: number;
}





/**
 * One active delivery line item (a service or an option) for a given date. Exactly one of delivery_list_service_id / delivery_list_option_id is non-null.
 */
export interface DeliveryRequestListResponseDeliveryList { 
    /**
     * delivery_list_services.id — set when this item is a service, null for options
     */
    delivery_list_service_id?: string;
    /**
     * delivery_list_options.id — set when this item is an option, null for services
     */
    delivery_list_option_id?: string;
    /**
     * Branch ID (foreign key)
     */
    branch_id: string;
    /**
     * Delivery date in ISO 8601 format (YYYY-MM-DD)
     */
    delivery_date: string;
    /**
     * Status of the delivery list
     */
    delivery_list_status: string;
    /**
     * Hospital ID (foreign key)
     */
    hospital_id: string;
    /**
     * Room ID associated with the delivery
     */
    room_id: string;
}






/**
 * Response body returned after a successful delivery request list retrieval.
 */
export interface CompletedDeliveryResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * List of delivery requests
     */
    delivery_request_list: Array<CompletedDeliveryResponseInfo>;
}






/**
 * Delivery request information returned in the delivery request list response.
 */
export interface CompletedDeliveryResponseInfo { 
    /**
     * ID of the delivery list
     */
    request_id: string;
    /**
     * \'2\' (ADMIN_STAFF) or \'3\' (HOSPITAL_STAFF)
     */
    user_type: string;
    /**
     * Room ID associated with the delivery; null for HOSPITAL_STAFF delivery lists
     */
    room_id?: string;
    /**
     * Room number; null for HOSPITAL_STAFF delivery lists
     */
    room_number?: string;
    room?: CompletedDeliveryRoom;
    /**
     * classification ID; populated for HOSPITAL_STAFF delivery lists
     */
    classification_id?: string;
    /**
     * Classification room ID; populated for HOSPITAL_STAFF delivery lists
     */
    classification_room_id?: string;
    /**
     * Classification name; populated for HOSPITAL_STAFF delivery lists
     */
    classification_name?: string;
    /**
     * Classification room number; populated for HOSPITAL_STAFF delivery lists
     */
    classification_room_number?: string;
    suspension_period?: CompletedDeliverySuspensionPeriod;
    /**
     * list of deliveries associated with this delivery requests
     */
    delivery_lists?: Array<CompletedDeliveryResponseDeliveryList>;
    completed_delivery_list_id?: string;
    delivery_date?: string;
    delivery_list_status?: string;
    delivery_list_service_id?: string | null;
    delivery_list_option_ids?: Array<string> | null;
    hospital_id?: string;
    hospital_name?: string;
    branch_id?: string;
    branch_name?: string;
    /**
     * Patient identifier
     */
    patient_id?: string;
    /**
     * Name of the patient
     */
    patient_name: string;
    /**
     * Kana name of the patient
     */
    kana_name: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    suburb?: string;
    remaining_address?: string;
    home_phone_number?: string;
    cell_phone_number?: string;
    /**
     * List of Service IDs with date ranges associated with the delivery request
     */
    service_ids: Array<CompletedDeliveryServiceIdModel>;
    /**
     * List of Option IDs with date ranges associated with the delivery request
     */
    options: Array<CompletedDeliveryOptionIdModel>;
    /**
     * start date of option
     */
    option_start_date?: string;
    /**
     * end date of option
     */
    option_end_date?: string;
    /**
     * Additional notes for the delivery request
     */
    notes?: string;
    /**
     * Billing deadline (締め日) of the hospital this delivery request belongs to
     */
    billing_deadline?: number;
}





/**
 * Suspension period associated with a HOSPITAL_STAFF delivery list.
 */
export interface CompletedDeliverySuspensionPeriod { 
    /**
     * Suspension start date (YYYY-MM-DD)
     */
    suspension_start_date: string;
    /**
     * Suspension end date (YYYY-MM-DD)
     */
    suspension_end_date: string;
}





/**
 * Delivery request information returned in the delivery request list response.
 */
export interface CompletedDeliveryResponseDeliveryList { 
    /**
     * ID of the delivery list
     */
    completed_delivery_list_id: string;
    /**
     * Branch ID (foreign key)
     */
    branch_id: string;
    /**
     * Delivery date in ISO 8601 format (YYYY-MM-DD)
     */
    delivery_date: string;
    /**
     * Status of the delivery list
     */
    delivery_list_status: string;
    /**
     * Hospital ID (foreign key)
     */
    hospital_id: string;
    /**
     * Hospital name
     */
    hospital_name: string;
    /**
     * Room ID associated with the delivery; null for HOSPITAL_STAFF delivery lists
     */
    room_id?: string;
    /**
     * delivery_list_options.id values this delivery covers; null when the line is a service
     */
    delivery_list_option_ids?: Array<string> | null;
    /**
     * delivery_list_services.id this delivery covers; null when the line is an option
     */
    delivery_list_service_id?: string | null;
}





/**
 * Option with quantity
 */
export interface CompletedDeliveryOptionIdModel {
    /**
     * delivery_list_options.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable options.option_id from the master record. Null for legacy records.
     */
    option_id?: string;
    /**
     * Master options.id UUID (delivery_list_options.source_option_id). Null for legacy records.
     */
    master_option_id?: string;
    /**
     * Option name
     */
    option_name?: string;
    /**
     * Option type: 日額 or 販売
     */
    option_type?: string;
    /**
     * Quantity of the option
     */
    quantity: number;
    /**
     * unit price of the option delivery
     */
    option_unit_price?: number;
    /**
     * Total number of delivery made in days
     */
    option_total_day_count?: number;
    /**
     * Total consolidated bill for this option delivery
     */
    option_total_bill?: number;
}





/**
 * Service with date range and sub-services
 */
export interface CompletedDeliveryServiceIdModel {
    /**
     * delivery_list_services.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable services.service_id from the master record. Null for legacy records.
     */
    service_id?: string;
    /**
     * Master services.id UUID (delivery_list_services.source_service_id). Null for legacy records.
     */
    master_service_id?: string;
    /**
     * Service start date
     */
    start_date: string;
    /**
     * Service end date
     */
    end_date: string;
    /**
     * Service name
     */
    service_name?: string;
    /**
     * unit price of this service delivery
     */
    service_unit_price?: number;
    /**
     * Total days count made for this service delivery
     */
    service_total_day_count?: number;
    /**
     * Total consolidated bill for this service delivery
     */
    service_total_bill?: number;
}





/**
 * Room information associated with the delivery request (ADMIN_STAFF delivery lists)
 */
export interface CompletedDeliveryRoom { 
    /**
     * id of the room; null for HOSPITAL_STAFF delivery lists
     */
    room_id?: string;
    /**
     * Floor name (e.g., 1階)
     */
    floor_number: string;
    /**
     * Route name (e.g., A-ルート)
     */
    route_name: string;
    /**
     * Building name (e.g., 西)
     */
    building_name: string;
    /**
     * Room numbers (e.g., [\'101\', \'201\'])
     */
    room_number: Array<string>;
}






/**
 * Response body returned after a successful total data for completed delivery retrieved.
 */
export interface CompletedDeliveryTotalDataResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Total number of days that has service delivery
     */
    service_day_count: number;
    /**
     * total bill computed for the service delivery
     */
    total_service_bill: number;
    /**
     * Total bill computed for all the option delivery
     */
    total_option_bill: number;
    /**
     * Total bill computed
     */
    total_bill: number;
}







/**
 * Response body for total count confirmation.
 */
export interface TotalCountConfirmationResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * List of services with aggregated set/size counts
     */
    services: Array<ServiceCountInfo>;
}






/**
 * A service with its sets and aggregated counts.
 */
export interface ServiceCountInfo { 
    /**
     * Service ID
     */
    service_id: string;
    /**
     * Service name
     */
    service_name: string;
    /**
     * List of sets with size counts under this service
     */
    sets: Array<SetCountInfo>;
}





/**
 * A set (item) with its size-based counts.
 */
export interface SetCountInfo { 
    /**
     * Name of the set (item)
     */
    set_name: string;
    /**
     * List of size counts for this set
     */
    size_counts: Array<SizeCountInfo>;
}





/**
 * Count of a specific set + size combination.
 */
export interface SizeCountInfo { 
    /**
     * Set ID
     */
    set_id: string;
    /**
     * Selected size
     */
    size: string;
    /**
     * Number of delivery requests with this set and size
     */
    count: number;
}






/**
 * Request body for creating a delivery request.
 */
export interface CreateDeliveryRequestRequest { 
    /**
     * Patient ID
     */
    patient_id: string;
    /**
     * Patient surname
     */
    patient_surname: string;
    /**
     * Patient given name
     */
    patient_name: string;
    /**
     * Patient kana surname
     */
    kana_surname: string;
    /**
     * Patient kana given name
     */
    kana_name: string;
    /**
     * Hospital ID
     */
    hospital_id: string;
    /**
     * Room ID (FK to rooms). Required for ADMIN_STAFF (role \'2\'); omit for HOSPITAL_STAFF.
     */
    room_id?: string;
    /**
     * Room number ID (FK to room_room_numbers). Required for ADMIN_STAFF (role \'2\'); omit for HOSPITAL_STAFF.
     */
    room_number_id?: string;
    /**
     * Classification ID (FK to hospital_classifications). Required for HOSPITAL_STAFF (role \'3\'); omit for ADMIN_STAFF.
     */
    classification_id?: string;
    /**
     * Classification room ID (FK to classification_rooms). Required for HOSPITAL_STAFF (role \'3\'); omit for ADMIN_STAFF.
     */
    classification_room_id?: string;
    /**
     * Suspension start date (YYYY-MM-DD). Required for HOSPITAL_STAFF (role \'3\').
     */
    suspension_start_date?: string;
    /**
     * Suspension end date (YYYY-MM-DD). Required for HOSPITAL_STAFF (role \'3\').
     */
    suspension_end_date?: string;
    /**
     * List of services with date ranges and sub-services
     */
    service_ids: Array<ServiceIdRequest>;
    /**
     * List of options with quantities and delivery dates
     */
    options: Array<OptionIdRequest>;
    /**
     * Patient postal code
     */
    postal_code?: string;
    /**
     * Patient prefecture
     */
    prefecture?: string;
    /**
     * Patient city
     */
    city?: string;
    /**
     * Patient suburb / district
     */
    suburb?: string;
    /**
     * Remaining address after city/suburb
     */
    remaining_address?: string;
    /**
     * Patient home phone number
     */
    home_phone_number?: string;
    /**
     * Patient cell phone number
     */
    cell_phone_number?: string;
    /**
     * Additional notes for the delivery request
     */
    notes?: string;
}





/**
 * Service with date range and sub-services
 */
export interface ServiceIdRequest { 
    /**
     * Service ID — delivery_list_services.id for existing rows, master services.service_id for new ones
     */
    service_id: string;
    /**
     * Service start date (YYYY-MM-DD)
     */
    start_date: string;
    /**
     * Service end date (YYYY-MM-DD); omit for open-ended services
     */
    end_date?: string;
    /**
     * List of sub-services (sets) under this service
     */
    sub_services: Array<SubServiceRequest>;
}





/**
 * Sub-service with set ID and size
 */
export interface SubServiceRequest { 
    /**
     * Set ID (master sets.set_id string)
     */
    set_id: string;
    /**
     * Size of the sub-service
     */
    size: string;
}





/**
 * Option with quantity and individual delivery date
 */
export interface OptionIdRequest { 
    /**
     * Option ID — delivery_list_options.id for existing rows, master options.id UUID for new ones
     */
    option_id: string;
    /**
     * Quantity of the option
     */
    quantity: number;
    /**
     * Date this option is to be delivered (YYYY-MM-DD)
     */
    option_delivery_date: string;
}






/**
 * Response body returned after a successful leader registration.
 */
export interface CreateDeliveryRequestResponse { 
    status_code: 200;
    result: 'OK';
    delivery_request: CreateDeliveryRequestResponseInfo;
    /**
     * id of the delivery_request that has been created
     */
    request_id: string;
    /**
     * id of the job that is creating the delivery_request and notify uid
     */
    job_id: string;
}






/**
 * Set data in the response
 */
export interface CreateDeliveryRequestResponseInfo { 
    /**
     * ID of the delivery request
     */
    request_id: string;
    /**
     * Room ID where the delivery is requested
     */
    room_id?: string;
    /**
     * Additional notes for the delivery request
     */
    notes?: string;
    /**
     * Timestamp when user was created (ISO 8601)
     */
    created_at: string;
    /**
     * Timestamp when user was last updated (ISO 8601)
     */
    updated_at: string;
}




/**
 * Request body for creating a billing contact for a delivery request.
 */
export interface CreateDeliveryBillingRequest {
    /**
     * id of the delivery request this billing contact belongs to (delivery_lists.id)
     */
    delivery_list_id: string;
    /**
     * Billing contact surname
     */
    billing_surname: string;
    /**
     * Billing contact given name
     */
    billing_name: string;
    /**
     * Billing contact kana surname
     */
    billing_kana_surname: string;
    /**
     * Billing contact kana given name
     */
    billing_kana_name: string;
    /**
     * Billing contact postal code
     */
    postal_code?: string;
    /**
     * Billing contact prefecture
     */
    prefecture?: string;
    /**
     * Billing contact city
     */
    city?: string;
    /**
     * Billing contact suburb / district
     */
    suburb?: string;
    /**
     * Billing contact remaining address after city/suburb
     */
    remaining_address?: string;
    /**
     * Billing contact home phone number
     */
    home_phone_number?: string;
    /**
     * Billing contact cell phone number
     */
    cell_phone_number?: string;
}




/**
 * Response body returned after a successful delivery billing creation.
 */
export interface CreateDeliveryBillingResponse {
    status_code: 200;
    result: 'OK';
    delivery_billing: CreateDeliveryBillingResponseInfo;
    /**
     * id of the delivery_billing that has been created
     */
    delivery_billing_id: string;
    /**
     * id of the job that is creating the delivery_billing and notify uid
     */
    job_id: string;
}




/**
 * Billing data in the response
 */
export interface CreateDeliveryBillingResponseInfo {
    /**
     * ID of the delivery billing
     */
    delivery_billing_id: string;
    /**
     * id of the delivery request this billing contact belongs to (delivery_lists.id)
     */
    delivery_list_id: string;
    billing_surname: string;
    billing_name: string;
    billing_kana_surname: string;
    billing_kana_name: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    suburb?: string;
    remaining_address?: string;
    home_phone_number?: string;
    cell_phone_number?: string;
}




export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for making a delivery completed.
 */
export interface MakeDeliveryCompletedRequest { 
    /**
     * either \'1\'=DELIVERED or \'2\'=NOTDELIVERED
     */
    delivery_list_status: string;
    /**
     * date of the delivery in YYYY-MM-DD format; defaults to today (JST) if omitted
     */
    delivery_date?: string;
    /**
     * id of the delivery list item (delivery_list_services.id or delivery_list_options.id)
     */
    list_id: string;
    /**
     * id of the delivery request (delivery_lists.id)
     */
    request_id: string;
}






/**
 * Response body returned after a successful to make a delivery completed.
 */
export interface MakeDeliveryCompletedResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the job that is completeing the delivery
     */
    job_id: string;
}




/**
 * Request body for updating a delivery request (full-replacement semantics). The frontend sends the complete desired state; the service diffs it against the current state and applies the minimum set of SQL operations. Exactly one location group must be populated, matching the original user_type: ADMIN_STAFF → room_id + room_number_id HOSPITAL_STAFF → classification_id + classification_room_id
 */
export interface UpdateDeliveryRequestRequest { 
    /**
     * delivery_lists.id to update
     */
    request_id: string;
    /**
     * rooms.id (UUID string). Required when the delivery list is ADMIN_STAFF type.
     */
    room_id?: string;
    /**
     * room_room_numbers.id (UUID string). Required when ADMIN_STAFF type.
     */
    room_number_id?: string;
    /**
     * hospital_classifications.id (UUID string). Required when HOSPITAL_STAFF type.
     */
    classification_id?: string;
    /**
     * classification_rooms.id (UUID string). Required when HOSPITAL_STAFF type.
     */
    classification_room_id?: string;
    /**
     * Patient surname
     */
    patient_surname: string;
    /**
     * Patient given name
     */
    patient_name: string;
    /**
     * Patient kana surname
     */
    kana_surname: string;
    /**
     * Patient kana given name
     */
    kana_name: string;
    /**
     * Complete list of services with date ranges for this delivery request
     */
    service_ids: Array<ServiceIdRequest>;
    /**
     * Complete list of options with quantities and individual delivery dates
     */
    options: Array<OptionIdRequest>;
    /**
     * Patient postal code
     */
    postal_code?: string;
    /**
     * Patient prefecture
     */
    prefecture?: string;
    /**
     * Patient city
     */
    city?: string;
    /**
     * Patient suburb / district
     */
    suburb?: string;
    /**
     * Remaining address after city/suburb
     */
    remaining_address?: string;
    /**
     * Patient home phone number
     */
    home_phone_number?: string;
    /**
     * Patient cell phone number
     */
    cell_phone_number?: string;
    /**
     * Additional notes for the delivery request
     */
    notes?: string;
}






/**
 * Response body returned after a successful delivery request update.
 */
export interface UpdateDeliveryRequestResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * ID of the delivery request that was updated
     */
    request_id: string;
    /**
     * Job ID for the update operation
     */
    job_id: string;
}




/**
 * 
 */
export interface GetAllDeliveryListsResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Total number of matching records
     */
    total_count: number;
    /**
     * Current page (1-based)
     */
    page: number;
    /**
     * Items per page
     */
    limit: number;
    items: Array<DeliveryListAdminLeaderItem>;
}






/**
 * 
 */
export interface DeliveryListAdminLeaderItem { 
    /**
     * delivery_lists.id
     */
    delivery_list_id: string;
    /**
     * Patient identifier
     */
    patient_id?: string;
    patient_surname: string;
    patient_name: string;
    kana_surname: string;
    kana_name: string;
    notes?: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    suburb?: string;
    remaining_address?: string;
    home_phone_number?: string;
    cell_phone_number?: string;
    room_id?: string;
    room_number_id?: string;
    room?: DLRoom;
    /**
     * hospital_classifications.id
     */
    classification_id?: string;
    /**
     * classification_rooms.id
     */
    classification_room_id?: string;
    hospital_id: string;
    /**
     * Hospital display name on frontend
     */
    hospital_name: string;
    branch_id: string;
    /**
     * Branch display name
     */
    branch_name: string;
    /**
     * \'2\' (ADMIN_STAFF) or \'3\' (HOSPITAL_STAFF)
     */
    user_type: string;
    full_delivery_completed: boolean;
    /**
     * Suspension start date (YYYY-MM-DD). Only set for HOSPITAL_STAFF delivery lists.
     */
    suspension_start_date?: string;
    /**
     * Suspension end date (YYYY-MM-DD). Only set for HOSPITAL_STAFF delivery lists.
     */
    suspension_end_date?: string;
    created_at: string;
    services: Array<DLServiceItem>;
    options: Array<DLOptionItem>;
}





/**
 * 
 */
export interface DLOptionItem {
    /**
     * delivery_list_options.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable options.option_id from the master record. Null for legacy records.
     */
    option_id?: string;
    /**
     * Master options.id UUID (delivery_list_options.source_option_id). Null for legacy records.
     */
    master_option_id?: string;
    /**
     * Delivery date (YYYY-MM-DD)
     */
    option_delivery_date: string;
    option_data: Array<DLOptionDataItem>;
}





/**
 * 
 */
export interface DLOptionDataItem { 
    /**
     * Display name of the option
     */
    option_name: string;
    /**
     * Unit price of the option
     */
    daily_price: number;
    /**
     * Quantity ordered
     */
    quantity: number;
}





/**
 * 
 */
export interface DLRoom { 
    room_id: string;
    building_name: string;
    floor_number: string;
    route_name: string;
    room_number: Array<string>;
}





/**
 * 
 */
export interface DLServiceItem {
    /**
     * delivery_list_services.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable services.service_id from the master record. Null for legacy records.
     */
    service_id?: string;
    /**
     * Master services.id UUID (delivery_list_services.source_service_id). Null for legacy records.
     */
    master_service_id?: string;
    /**
     * Display name of the service
     */
    service_name: string;
    /**
     * Service start date (YYYY-MM-DD)
     */
    start_date: string;
    /**
     * Service end date (YYYY-MM-DD). Null means ongoing.
     */
    end_date?: string;
    /**
     * Daily price of the service
     */
    daily_price: number;
    sets: Array<DLSetItem>;
}





/**
 * 
 */
export interface DLSetItem {
    /**
     * delivery_list_service_sets.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable sets.set_id, denormalized onto delivery_list_service_sets.set_id
     */
    set_id: string;
    /**
     * Master sets.id UUID (delivery_list_service_sets.source_set_id). Null for legacy records.
     */
    master_set_id?: string;
    /**
     * Display name of the set
     */
    set_name: string;
    /**
     * Size category
     */
    size: string;
}




export interface ErrorMessage403 {
  status_code: 403;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * 
 */
export interface nkStaffDeliveryResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Total matching records
     */
    total_count: number;
    /**
     * List of delivery list records
     */
    delivery_request_list: Array<nkStaffDeliveryItem>;
}






/**
 * One delivery list record (groups all CDL items for the patient/date).
 */
export interface nkStaffDeliveryItem { 
    /**
     * delivery_lists.id
     */
    request_id: string;
    hospital_id: string;
    hospital_name: string;
    branch_id: string;
    room_id: string;
    room_number: string;
    room: nkStaffDeliveryRoom;
    delivery_lists: Array<nkStaffDeliveryListItem>;
    /**
     * Patient identifier
     */
    patient_id?: string;
    patient_surname: string;
    patient_name: string;
    kana_surname: string;
    kana_name: string;
    postal_code?: string;
    prefecture?: string;
    city?: string;
    suburb?: string;
    remaining_address?: string;
    home_phone_number?: string;
    cell_phone_number?: string;
    service_ids: Array<nkStaffDeliveryService>;
    options: Array<nkStaffDeliveryOption>;
    notes?: string;
}





/**
 * 
 */
export interface nkStaffDeliveryOption {
    /**
     * delivery_list_options.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable options.option_id from the master record. Null for legacy records.
     */
    option_id?: string;
    /**
     * Master options.id UUID (delivery_list_options.source_option_id). Null for legacy records.
     */
    master_option_id?: string;
    option_name?: string;
    /**
     * Quantity of the option
     */
    quantity: number;
    /**
     * Option delivery date (YYYY-MM-DD)
     */
    option_delivery_date: string;
    /**
     * Daily price of the option (delivery_list_option_data.daily_price).
     */
    option_price?: number;
}





/**
 * One active delivery line (service or option) for a given date.
 */
export interface nkStaffDeliveryListItem { 
    delivery_list_service_id?: string;
    delivery_list_option_id?: string;
    branch_id: string;
    hospital_id: string;
    room_id: string;
    /**
     * Delivery date (YYYY-MM-DD)
     */
    delivery_date: string;
    /**
     * CDL status: \'0\' PENDING, \'1\' DELIVERED, \'2\' NOTDELIVERED
     */
    delivery_status: string;
}





/**
 * 
 */
export interface nkStaffDeliveryRoom { 
    room_id: string;
    floor_number: string;
    route_name: string;
    building_name: string;
    room_number: Array<string>;
}





/**
 * 
 */
export interface nkStaffDeliveryService { 
    /**
     * delivery_list_services.id — the row on this delivery request; use this for any update, delete or reference
     */
    id: string;
    /**
     * Human-readable services.service_id from the master record. Null for legacy records.
     */
    service_id?: string;
    /**
     * Master services.id UUID (delivery_list_services.source_service_id). Null for legacy records.
     */
    master_service_id?: string;
    /**
     * Service start date (YYYY-MM-DD)
     */
    start_date: string;
    /**
     * Service end date (YYYY-MM-DD) or empty string
     */
    end_date: string;
    service_name?: string;
    /**
     * Daily price of the service (delivery_list_services.daily_price).
     */
    service_price?: number;
}

