/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after a successful dropdown list retrieval.
 */
export interface DropdownListResponse { 
    status_code: 200;
    result: 'OK';
    dropdown_list: { [key: string]: DropdownPageInfo; }
;
}





/**
 * Paginated wrapper for a single dropdown table.
 */
export interface DropdownPageInfo { 
    items: Array<DropdownResponseInfo>;
    total_count: number;
    /**
     * Pass as \'after\' in the next request — null means no more pages
     */
    next_cursor?: number;
}





/**
 * Option information returned in the dropdown list response.
 */
export interface DropdownResponseInfo { 
    /**
     * ID of the dropdown
     */
    field_id: string;
    /**
     * Dropdown name
     */
    field_name: string;
    /**
     * Type of the set (only for sets dropdown)
     */
    type?: string;
    /**
     * Daily price of the service (only for services dropdown)
     */
    daily_price?: string;
    /**
     * Floor name of the room (only for rooms dropdown)
     */
    floor_number?: string;
    /**
     * Building name of the room (only for rooms dropdown)
     */
    building_name?: string;
    /**
     * Room numbers with IDs — populated only when id=<room_uuid> is passed
     */
    room_number?: Array<RoomNumberInfo>;
    /**
     * Route name of the room (e.g., A-ルート)
     */
    route_name?: string;
}





/**
 * Single room number entry with its own ID.
 */
export interface RoomNumberInfo { 
    id: string;
    room_number: string;
}




export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}

