/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after a successful hospital list retrieval.
 */
export interface HospitalListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * List of hospitals
     */
    hospital_list: Array<HospitalListResponseInfo>;
}






/**
 * Hospital information returned in the hospital list response.
 */
export interface HospitalListResponseInfo { 
    /**
     * primary key of the hospital
     */
    id: string;
    /**
     * User defined ID of the hospital
     */
    hospital_id: string;
    /**
     * Short code for the hospital
     */
    hospital_code: string;
    /**
     * Hospital name
     */
    hospital_name: string;
    /**
     * Branch ID (foreign key)
     */
    branch_id?: string;
    /**
     * Branch name
     */
    branch_name?: string;
    /**
     * Contract status: 担当中 or 非担当
     */
    contract_status?: string;
    /**
     * Type of user associated with the hospital
     */
    user_type: string;
    /**
     * Whether to show the delivery button for this hospital
     */
    show_delivery_button: string;
    /**
     * Billing classification (e.g. 個人, 法人)
     */
    billing_classification?: string;
    /**
     * Payment method used for billing
     */
    payment_method?: string;
    /**
     * Billing closing day of the month (10, 15, or 31)
     */
    billing_deadline?: number;
}




export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * 
 */
export interface CreateHospitalRequest { 
    /**
     * Short code for the hospital (4-8 characters), unique within a branch
     */
    hospital_code: string;
    /**
     * ID of the hospital
     */
    hospital_id: string;
    /**
     * Name of the hospital
     */
    hospital_name: string;
    /**
     * ID of the branch associated with it
     */
    branch_id: string;
    /**
     * Contract status: \'1\' = in charge, \'0\' = not in charge
     */
    contract_status?: string;
    /**
     * Type of user associated with the hospital: \'2\' = ADMIN_STAFF, \'3\' = HOSPITAL_STAFF
     */
    user_type: string;
    /**
     * Whether to show the delivery button. Required when user_type is ADMIN_STAFF.
     */
    show_delivery_button?: boolean;
    /**
     * Classification name. Required when user_type is HOSPITAL_STAFF.
     */
    category?: string;
    /**
     * Room numbers for the classification. Required (may be empty list) when user_type is HOSPITAL_STAFF.
     */
    room_number: Array<string>;
    /**
     * Billing classification (e.g. 個人, 法人)
     */
    billing_classification?: string;
    /**
     * Payment method used for billing
     */
    payment_method?: string;
    /**
     * Billing closing day of the month (10, 15, or 31)
     */
    billing_deadline?: number;
}






/**
 * Response body returned after a successful hospital creation.
 */
export interface CreateHospitalResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the job that is creating the user and notify uid
     */
    job_id: string;
}







/**
 * Request body of hospital update
 */
export interface HospitalUpdateRequest { 
    /**
     * ID of the branch
     */
    branch_id: string;
    /**
     * Name of the hospital branch
     */
    branch_name?: string;
    /**
     * Required Hospital ID
     */
    hospital_id: string;
    /**
     * New name of the hospital
     */
    hospital_name?: string;
    /**
     * Contract status: \'1\' = in charge, \'0\' = not in charge
     */
    contract_status?: string;
    /**
     * User ID to remove access from this hospital
     */
    remove_user_access?: string;
    /**
     * Type of user associated with the hospital: \'2\' = ADMIN_STAFF, \'3\' = HOSPITAL_STAFF
     */
    user_type?: string;
    /**
     * Whether to show the delivery button for this hospital
     */
    show_delivery_button?: boolean;
    /**
     * Category of the hospital
     */
    category?: string;
    /**
     * Number of rooms in the hospital
     */
    room_number?: Array<string>;
    /**
     * Billing classification (e.g. 個人, 法人)
     */
    billing_classification?: string;
    /**
     * Payment method used for billing
     */
    payment_method?: string;
    /**
     * Billing closing day of the month (10, 15, or 31)
     */
    billing_deadline?: number;
}






/**
 * Response body returned after successfully updating branch.
 */
export interface HospitalUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Hospital update api response
     */
    message: string;
    /**
     * id of the job that is creating the branch and notify uid
     */
    job_id: string;
}




/**
 * Request body for hospital password reset.
 */
export interface UpdatePasswordRequest { 
    /**
     * id of the branch, used for staff login
     */
    branch_id: string;
    /**
     * id of the hospital, used for staff login
     */
    hospital_id: string;
    /**
     * Old password of the user
     */
    old_password?: string;
    /**
     * New password of the user
     */
    new_password: string;
}






/**
 * Response body returned after a successful hospital password reset.
 */
export interface UpdatePasswordResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * password reset success message
     */
    message: string;
    /**
     * ID of the background job handling the password reset
     */
    job_id: string;
}




/**
 * Response body returned after a successful hospital password retrieval.
 */
export interface HospitalPasswordResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * hospital id
     */
    hospital_id: string;
    /**
     * hospital password
     */
    password?: string;
}




/**
 * 
 */
export interface ClassificationCreateRequest { 
    /**
     * UUID of the hospital (must be HOSPITAL_STAFF type)
     */
    hospital_id: string;
    /**
     * UUID of the branch the hospital belongs to
     */
    branch_id: string;
    /**
     * Name of the new classification
     */
    classification_name: string;
    /**
     * Room numbers to associate with this classification
     */
    room_numbers: Array<string>;
}






/**
 * 
 */
export interface ClassificationCreateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * UUID of the newly created classification
     */
    classification_id: string;
    /**
     * Background job ID for the creation operation
     */
    job_id: string;
}




/**
 * 
 */
export interface ClassificationSearchResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Total matching classifications
     */
    total_count: number;
    classifications: Array<ClassificationItem>;
}






/**
 * 
 */
export interface ClassificationItem { 
    /**
     * UUID of the classification
     */
    classification_id: string;
    /**
     * UUID of the hospital
     */
    hospital_id: string;
    /**
     * Classification name
     */
    classification_name: string;
    /**
     * Rooms under this classification
     */
    rooms: Array<ClassificationRoomItem>;
}





/**
 * 
 */
export interface ClassificationRoomItem { 
    /**
     * UUID of the classification room
     */
    room_id: string;
    /**
     * Room number string
     */
    room_number: string;
}




/**
 * 
 */
export interface ClassificationUpdateRequest { 
    /**
     * UUID of the classification to update
     */
    classification_id: string;
    /**
     * New name for the classification (omit to keep existing)
     */
    classification_name?: string;
    /**
     * Full replacement list of room numbers (omit to keep existing rooms unchanged)
     */
    room_numbers?: Array<string>;
}






/**
 * 
 */
export interface ClassificationUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Background job ID for the update operation
     */
    job_id: string;
}

