/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned when querying user information.
 */
export interface JobStatusCheckResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Status of job completion
     */
    status: boolean;
    /**
     * Status of the job on SQS.         Possible values: PENDING, IN_PROGRESS, SUCCESS, FAILED, RETRYING, DEAD         
     */
    status_type: string;
}





export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}

