/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned.
 */
export interface LeaderListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * Id of newly created leader
     */
    leader_list: Array<LeaderListResponseLeader>;
}






/**
 * Leader list returned.
 */
export interface LeaderListResponseLeader { 
    /**
     * partition key of the leader
     */
    id: string;
    /**
     * ID of the leader
     */
    leader_id: string;
    /**
     * Type of the branch id
     */
    branch_id: string;
    /**
     * Type of the branch name
     */
    branch_name?: string;
    /**
     * Email of the leader
     */
    leader_email?: string;
    /**
     * Number of hospital of that user
     */
    hospital_number?: number;
    /**
     * leader name
     */
    leader_name: string;
}






/**
 * Request body for leader.
 */
export interface CreateLeaderRequest { 
    /**
     * Branch ID of the leader
     */
    branch_id: string;
    /**
     * Name of the leader
     */
    leader_name: string;
    /**
     * Unique Email address of the user
     */
    email: string;
    /**
     * Hospital list of the leader
     */
    hospital_list?: Array<string>;
    /**
     * Hashed password of the user
     */
    password: string;
}






/**
 * Response body returned after a successful leader registration.
 */
export interface CreateLeaderResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the leader that has been created
     */
    leader_id: string;
    /**
     * id of the job that is creating the leader and notify uid
     */
    job_id: string;
}





export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body of leader update
 */
export interface LeaderUpdateRequest { 
    /**
     * Leader ID
     */
    leader_id: string;
    /**
     * Hospital list of the leader
     */
    hospital_list?: Array<string>;
    /**
     * Name of the leader
     */
    leader_name: string;
    /**
     * Hashed password of the user
     */
    password: string;
}






/**
 * Response body returned after successfully updating branch.
 */
export interface LeaderUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Leader update api response
     */
    message: string;
    /**
     * id of the job that is creating the branch and notify uid
     */
    job_id: string;
}




/**
 * Response body returned after a successful leader details retrieval.
 */
export interface LeaderDetailsResponse { 
    status_code: 200;
    result: 'OK';
    leader_details: LeaderDetailsResponseInfo;
}






/**
 * Leader information returned in the leader details response.
 */
export interface LeaderDetailsResponseInfo { 
    /**
     * partition key of the leader
     */
    id: string;
    /**
     * ID of the leader
     */
    leader_id: string;
    /**
     * Type of the branch id
     */
    branch_id: string;
    /**
     * Type of the branch name
     */
    branch_name?: string;
    /**
     * Email of the leader
     */
    leader_email?: string;
    /**
     * List of hospital IDs of that user
     */
    hospital_list?: Array<string>;
    /**
     * leader name
     */
    leader_name: string;
}

