/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * 
 */
export interface OptionListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Total number of options matching the query
     */
    total_count: number;
    /**
     * List of options retrieved
     */
    option_list: Array<OptionListResponseInfo>;
}






/**
 * 
 */
export interface OptionListResponseInfo { 
    /**
     * Primary key UUID of the option
     */
    id: string;
    /**
     * ID of the option
     */
    option_id: string;
    /**
     * Option name
     */
    option_name: string;
    /**
     * Option price
     */
    price: number;
}




export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Response body returned after a successful option details retrieval.
 */
export interface OptionDetailsResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * List of option details retrieved
     */
    option_details: Array<OptionDetailsResponseInfo>;
}






/**
 * Option information returned in the option details response.
 */
export interface OptionDetailsResponseInfo { 
    /**
     * Primary key UUID of the option
     */
    id: string;
    /**
     * ID of the option
     */
    option_id: string;
    /**
     * Option name
     */
    option_name: string;
    /**
     * Option price
     */
    price: number;
}




/**
 * Request body for option creation.
 */
export interface CreateOptionRequest { 
    /**
     * Option ID
     */
    option_id: string;
    /**
     * Option name
     */
    option_name: string;
    /**
     * Option price (tax included)
     */
    price: number;
}






/**
 * 
 */
export interface CreateOptionResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * ID of the option that was created
     */
    id: string;
    /**
     * ID of the job handling the option creation
     */
    job_id: string;
}


export interface ErrorMessage403 {
  status_code: 403;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body of option update
 */
export interface OptionUpdateRequest { 
    /**
     * Required option record ID to be updated
     */
    id: string;
    /**
     * Option ID
     */
    option_id: string;
    /**
     * New name of the option
     */
    option_name?: string;
    /**
     * Price (tax included)
     */
    price?: number;
}






/**
 * 
 */
export interface OptionUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Result message for the option update
     */
    message: string;
    /**
     * ID of the job handling the option update
     */
    job_id: string;
}

