/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after a successful room list retrieval.
 */
export interface RoomListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * List of rooms
     */
    data: Array<RoomListResponseInfo>;
}






/**
 * Room information returned in the room list response.
 */
export interface RoomListResponseInfo { 
    /**
     * Partition key of room table
     */
    id: string;
    /**
     * Foreign key referencing the hospital
     */
    hospital_id: string;
    /**
     * Floor number (e.g., 1階)
     */
    floor_number: string;
    /**
     * Route name (e.g., A-ルート)
     */
    route_name: string;
    /**
     * Building name (e.g., 西)
     */
    building_name: string;
    /**
     * Room numbers (e.g., [\'101\', \'201\'])
     */
    room_number: Array<string>;
    /**
     * Available days (0=Sun, 1=Mon, ..., 6=Sat)
     */
    available_days: Array<number>;
}




export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for room creation.
 */
export interface CreateRoomRequest { 
    /**
     * Hospital ID (foreign key)
     */
    hospital_id: string;
    /**
     * Branch ID (foreign key)
     */
    branch_id: string;
    /**
     * Floor number (e.g., 1階)
     */
    floor_number?: string;
    /**
     * Route name (e.g., A-ルート)
     */
    route_name?: string;
    /**
     * Building name (e.g., 西棟)
     */
    building_name?: string;
    /**
     * Room numbers (e.g., [\'101\', \'201\'])
     */
    room_number?: Array<string>;
    /**
     * Available days (0=Sun, 1=Mon, ..., 6=Sat)
     */
    available_days?: Array<number>;
}






/**
 * Response body returned after successful room creation.
 */
export interface CreateRoomResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the job creating the room
     */
    job_id: string;
}







/**
 * Request body for room creation.
 */
export interface UpdateRoomRequest { 
    /**
     * Partition key of room table
     */
    id: string;
    /**
     * Hospital ID (foreign key)
     */
    hospital_id: string;
    /**
     * Floor number (e.g., 1階)
     */
    floor_number?: string;
    /**
     * Route name (e.g., A-ルート)
     */
    route_name?: string;
    /**
     * Building name (e.g., 西棟)
     */
    building_name?: string;
    /**
     * Room numbers (e.g., [\'101\', \'201\'])
     */
    room_number?: Array<string>;
    /**
     * Available days (0=Sun, 1=Mon, ..., 6=Sat)
     */
    available_days?: Array<number>;
}






/**
 * Response body returned after successfully updating room.
 */
export interface RoomUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Room update api response
     */
    message: string;
    /**
     * id of the job that is creating the room and notify uid
     */
    job_id: string;
}

