/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after a successful user login.
 */
export interface ServiceListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * Id of newly created user
     */
    service_list: Array<ServiceListResponseService>;
}






/**
 * Service information returned upon successful login.
 */
export interface ServiceListResponseService { 
    /**
     * partition key of the service
     */
    id: string;
    /**
     * ID of the service
     */
    service_id: string;
    /**
     * Daily price of the service (stored as string)
     */
    daily_price: string;
    /**
     * Service name
     */
    service_name: string;
}






/**
 * Request body for creating a service.
 */
export interface CreateServiceRequest { 
    /**
     * Daily price of the service (stored as string)
     */
    daily_price: string;
    /**
     * Service ID
     */
    service_id: string;
    /**
     * Service name
     */
    service_name: string;
}






/**
 * Response body returned after a successful service creation.
 */
export interface CreateServiceResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the service that has been created
     */
    service_id: string;
    /**
     * id of the job that is creating the service
     */
    job_id: string;
}





export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for updating a service.
 */
export interface UpdateServiceRequest { 
    /**
     * Daily price of the service (stored as string)
     */
    daily_price?: string;
    /**
     * partition key of the service
     */
    id: string;
    /**
     * User defined id of the service
     */
    service_id: string;
    /**
     * Name of the service
     */
    service_name?: string;
}






/**
 * Response body returned after successfully updating service.
 */
export interface ServiceUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Service update api response
     */
    message: string;
    /**
     * id of the job that is creating the service and notify uid
     */
    job_id: string;
}

