/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body for session list endpoint.
 */
export interface SessionListResponse {
    status_code: 200;
    result: 'OK';
    /**
     * Total number of sessions
     */
    total_count: number;
    /**
     * Page currently returned (1-based)
     */
    current_page: number;
    /**
     * Total number of pages available
     */
    total_pages: number;
    /**
     * Whether a page after the current one exists
     */
    has_next: boolean;
    /**
     * Whether a page before the current one exists
     */
    has_previous: boolean;
    /**
     * List of session items
     */
    sessions: Array<SessionListResponseItem>;
}






/**
 * Single session item in the list response.
 */
export interface SessionListResponseItem { 
    /**
     * Session ID
     */
    session_id: string;
    /**
     * Branch ID
     */
    branch_id: string;
    /**
     * User ID
     */
    user_id: string;
    /**
     * Browser UUID
     */
    device_id: string;
    /**
     * Client IP address
     */
    ip_address: string;
    /**
     * Browser User-Agent
     */
    user_agent: string;
    /**
     * Login timestamp (JST)
     */
    login_time: string;
    /**
     * Session active status
     */
    is_active: string;
}




export interface ErrorMessage403 {
  status_code: 403;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for deactivating a user.
 */
export interface DeactivateUserRequest { 
    /**
     * Branch ID of the user to deactivate
     */
    branch_id: string;
    /**
     * User ID to deactivate
     */
    user_id: string;
}






/**
 * Response body for user deactivation endpoint.
 */
export interface DeactivateUserResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Success message
     */
    message: string;
    /**
     * ID of the deactivated user
     */
    user_id: string;
    /**
     * Deprecated. Deactivation is now applied synchronously against PostgreSQL, so there is no background job to poll. Always empty.
     */
    job_id: string;
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for force-logging out a session.
 */
export interface ForceLogoutRequest { 
    /**
     * Session ID to force logout
     */
    session_id: string;
}






/**
 * Response body for force logout endpoint.
 */
export interface ForceLogoutResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Success message
     */
    message: string;
    /**
     * Session ID that was force logged out
     */
    session_id: string;
}

