/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Response body returned after a successful user login.
 */
export interface SetListResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * total number of data found
     */
    total_count: number;
    /**
     * Id of newly created user
     */
    set_list: Array<SetListResponseSet>;
}






/**
 * Set information return sub service list.
 */
export interface SetListResponseSet { 
    /**
     * Partition key of the set
     */
    id: string;
    /**
     * User defined id of the set
     */
    set_id: string;
    /**
     * Type of the set
     */
    type: string;
    /**
     * Set name
     */
    set_name: string;
    /**
     * Set size
     */
    size: string;
    /**
     * Set status
     */
    set_status: string;
}






/**
 * Request body for sub service.
 */
export interface CreateSetRequest { 
    /**
     *  ID of the set table 
     */
    service_id: string;
    /**
     * User defined id of the set
     */
    set_id: string;
    /**
     * Name of the set
     */
    set_name: string;
    /**
     * comma separated sizes of the set
     */
    size: string;
    /**
     * Set type
     */
    type: string;
    /**
     * Set status (1: 使用中, 0: 非使用)
     */
    set_status: string;
}






/**
 * Response body returned after a successful set creation.
 */
export interface CreateSetResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * id of the set that has been created
     */
    set_id: string;
    /**
     * id of the job that is creating the set and notify uid
     */
    job_id: string;
}





export interface ErrorMessage400 {
  status_code: 400;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}


export interface ErrorMessage404 {
  status_code: 404;
  result: 'NG';
  /** Represents error message. */
  message: 'string';
}




/**
 * Request body for sub service.
 */
export interface UpdateSetRequest { 
    /**
     * Partition key of the set
     */
    id: string;
    /**
     * Set ID
     */
    set_id: string;
    /**
     * Name of the set
     */
    set_name?: string;
    /**
     * Size of the set
     */
    size?: string;
    /**
     * Set status (1: 使用中, 0: 非使用)
     */
    set_status?: string;
    /**
     * Set type
     */
    type?: string;
}






/**
 * Response body returned after successfully updating set.
 */
export interface SetUpdateResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * Set update api response
     */
    message: string;
    /**
     * id of the job that is creating the set and notify uid
     */
    job_id: string;
}

