/**
 * NK Fashion API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */





/**
 * Request body of new user registration
 */
export interface UserRegisterRequest { 
    /**
     * Unique Email address of the user
     */
    email: string;
    /**
     * Full name of the user
     */
    full_name: string;
    /**
     * Hashed password of the user
     */
    password: string;
}






/**
 * Response body returned after successfully registering a new user.
 */
export interface UserRegisterResponse { 
    status_code: 200;
    result: 'OK';
    user: UserRegisterResponseUser;
    /**
     * id of the user that has been created
     */
    user_id: string;
    /**
     * id of the job that is creating the user and notify uid
     */
    job_id: string;
}






/**
 * User data in the response
 */
export interface UserRegisterResponseUser { 
    /**
     * Full name of the user
     */
    full_name: string;
    /**
     * Timestamp of the user\'s last login (JST)
     */
    last_login: string;
    /**
     * Hashed password of the user
     */
    password_hash: string;
    /**
     * Role of the user (管理者 | リーダー | スタッフ)
     */
    role: string;
    /**
     * User email.
     */
    user_email: string;
    /**
     * User status (使用中 | 非使用)
     */
    user_status: string;
}






/**
 * Request body for user password reset.
 */
export interface ForgetPasswordRequest { 
    /**
     * Old password of the user
     */
    old_password: string;
    /**
     * New password of the user
     */
    new_password: string;
}






/**
 * Response body returned after a successful user password reset.
 */
export interface ForgetPasswordResponse { 
    status_code: 200;
    result: 'OK';
    /**
     * password reset success message
     */
    message: string;
    /**
     * ID of the background job handling the password reset
     */
    job_id: string;
}




