/* eslint-disable @typescript-eslint/typedef */

// ─── Shared strings reused across multiple label objects ───────────────────
export const CommonLabels = {
  // UI actions
  YEN_KANJI: 'Rs.',
  DAY_KANJI: 'days',
  SEARCH_PLACEHOLDER: 'Search...',
  ADD: 'Add',
  SAVE: 'Save',
  UPDATE: 'Update',
  DELETE: 'Delete',
  EDIT: 'Edit',
  BACK: 'Back',
  SELECT: 'Select',
  SORT: 'Sort',
  CLOSE: 'Close',
  CLEAR: 'Clear',
  // Form placeholders
  ID_PLACEHOLDER: 'ID',
  NAME_PLACEHOLDER: 'Name',
  YEN_PLACEHOLDER: 'Price',
  NOTES_PLACEHOLDER: 'Enter notes...',
  // Auth
  PASSWORD: 'Password',
  ENTER_PASSWORD: 'Enter your password',
  PASSWORD_MISMATCH: 'Passwords do not match',
  LOGIN: 'Login',
  LOGIN_IMAGE_ALT: 'NK Fashions Login',
  // Select prompts
  PLEASE_SELECT: 'Please select',
  PLEASE_SELECT_KANJI: 'Please select',
  PLEASE_SELECT_BRANCH: 'Select store location',
  // Branch / Hospital / Retail Locations
  BRANCH: 'Store / Warehouse',
  BRANCH_ID: 'Store ID',
  BRANCH_CODE: 'Store Code',
  ENTER_BRANCH_CODE: 'Enter store code',
  BRANCH_NAME: 'Store Name',
  ENTER_BRANCH_NAME: 'Enter store name',
  HOSPITAL_ID: 'Product ID',
  HOSPITAL_CODE: 'SKU Code',
  ENTER_HOSPITAL_CODE: 'Enter SKU code',
  HOSPITAL_NAME: 'Product Name',
  ENTER_HOSPITAL_ID: 'Enter product ID',
  SELECT_HOSPITAL: 'Select Product',
  // Location
  ROOM: 'Rack / Shelf',
  ROOM_NUMBER: 'Rack Number',
  FLOOR_NUMBER: 'Floor Number',
  FLOOR_SUFFIX: 'F',
  ROUTE_NAME: 'Channel / Category',
  BUILDING: 'Section / Zone',
  CATEGORY: 'Category',
  ADDRESS: 'Address',
  PHONE_NUMBER: 'Phone Number',
  POSTAL_CODE: 'Postal Code',
  PREFECTURE: 'State / Province',
  CITY: 'City',
  STREET_ADDRESS: 'Street Address',
  BUILDING_ROOM_NUMBER: 'Suite / Apt / Unit',
  HOME_PHONE: 'Home',
  MOBILE_PHONE: 'Mobile',
  // Service / Product Details
  SERVICE_NAME: 'Product / Plan Name',
  SERVICE_START_DATE: 'Start Date',
  SERVICE_END_DATE: 'End Date',
  SERVICE_START_USE_DATE: 'Active From',
  SERVICE_END_USE_DATE: 'Active Until',
  SERVICE_USAGE_DAYS: 'Active Days',
  // Option
  OPTION_NAME: 'Option / Add-on Name',
  OPTION_NAME_SALE: 'Option (Retail)',
  OPTION_NAME_SALE_HALF: 'Option (Retail)',
  OPTION_TYPE: 'Option Type',
  OPTION_START_DATE: 'Start Date',
  OPTION_END_DATE: 'End Date',
  // Quantity / Price / Date
  QUANTITY: 'Quantity',
  QUANTITY_UNIT: 'pcs',
  PRICE: 'Price',
  DATE: 'Date',
  DATE_PLACEHOLDER: 'Select date',
  SALE_DATE: 'Sale Date',
  DELIVERY_DATE: 'Shipping Date',
  DELIVERED: 'Fulfilled',
  NOT_DELIVERED: 'Pending',
  // Sets / Items
  SET_ID: 'Set ID',
  SET_NAME: 'Set Name',
  ITEM_NAME_SIZE: 'Item Name / Size',
  SIZE: 'Size',
  TYPE: 'Type',
  // Customer info
  PATIENT_ID: 'Customer ID',
  PATIENT_NAME: 'Customer Name',
  PATIENT_NOTES: 'Customer Notes:',
  KANA_NAME: 'Alternate Name',
  KANA_NAME_HIRAGANA: 'Phonetic Name',
  ENTER_PATIENT_ID: 'Enter customer ID',
  ENTER_PATIENT_NAME: 'Enter customer name',
  ENTER_KANA_NAME: 'Enter alternate name',
  // Pagination
  DISPLAY_10_ITEMS: 'Show 10',
  DISPLAY_20_ITEMS: 'Show 20',
  DISPLAY_50_ITEMS: 'Show 50',
  DISPLAY_100_ITEMS: 'Show 100',
  LOADING: 'Loading...',
  JOB_IN_PROGRESS: 'In Progress',
  NO_DATA: 'No records found',
  // Confirmation dialogs
  YES_TEXT: 'Yes (Y)',
  NO_TEXT: 'No (N)',
  DELETE_CONFIRM_MESSAGE: 'This action cannot be undone. Are you sure you want to delete this record?',
  CSV_CONFIRM_MESSAGE: 'Export record list as CSV file?',
  DELIVER_CONFIRM_MESSAGE: 'Mark order fulfillment as complete?',
  NO_DELIVERY_CONFIRM_MESSAGE: 'Mark order as unfulfilled / cancelled?',
  // Global auth errors
  SESSION_EXPIRED_MESSAGE: 'Your session has expired.\nPlease log in again.',
  SERVER_ERROR_MESSAGE: 'A server error occurred. Please try again.',
} as const;

export const BranchLabels = {
  TITLE: 'Stores & Warehouses',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  BRANCH_ID: CommonLabels.BRANCH_ID,
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  ADDRESS: CommonLabels.ADDRESS,
  UPDATE_BRANCH: 'Update Store Location',
  CREATE_BRANCH: 'Register Store Location',
  ENTER_BRANCH_ID: 'Enter store ID',
  ENTER_BRANCH_NAME: CommonLabels.ENTER_BRANCH_NAME,
  BRANCH_CODE: CommonLabels.BRANCH_CODE,
  ENTER_BRANCH_CODE: CommonLabels.ENTER_BRANCH_CODE,
  BRANCH_CODE_MIN_LENGTH: 'Store code must be at least 4 characters',
  ENTER_ADDRESS: 'Enter street address',
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const HospitalLabels = {
  TITLE: 'Products Catalog',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  USAGE_STATUS: 'Status',
  ADD: CommonLabels.ADD,
  HOSPITAL_ID: CommonLabels.HOSPITAL_ID,
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  HOSPITAL_CODE: 'SKU Code',
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  USER_TYPE: 'User Role',
  DELIVERY_STATUS: 'Order Status',
  CONTRACT_STATUS: 'Listing Status',
  IN_CHARGE: 'Active',
  NOT_IN_CHARGE: 'Inactive',
  HOSPITAL_REGISTRATION: 'Register Product',
  ENTER_HOSPITAL_ID: CommonLabels.ENTER_HOSPITAL_ID,
  ENTER_HOSPITAL_CODE: CommonLabels.ENTER_HOSPITAL_CODE,
  HOSPITAL_CODE_INVALID: 'SKU code must be between 4 and 8 characters',
  ENTER_HOSPITAL_NAME: 'Enter product name',
  PLEASE_SELECT: CommonLabels.PLEASE_SELECT,
  SELECT_BRANCH: 'Select store location',
  SELECT_USER_TYPE: 'Select user type',
  ADMIN_STAFF: 'Central Staff',
  ADMIN_STAFF_BUTTON_ACTIVE: 'Show Fulfill Button',
  ADMIN_STAFF_BUTTON_INACTIVE: 'Hide Fulfill Button',
  HOSPITAL_STAFF: 'Store Cashier',
  DELIVERY_BUTTON: 'Order Button Display',
  DELIVERY_BUTTON_SHOW: 'Show Button',
  DELIVERY_BUTTON_HIDE: 'Hide Button',
  SELECT_DELIVERY_BUTTON: 'Select button preference',
  CATEGORY: CommonLabels.CATEGORY,
  ENTER_CATEGORY: 'Enter category name',
  BILLING_CLASSIFICATION: 'Billing Classification',
  ENTER_BILLING_CLASSIFICATION: 'Enter billing classification',
  PAYMENT_METHOD: 'Payment Method',
  ENTER_PAYMENT_METHOD: 'Enter payment method',
  BILLING_DEADLINE: 'Billing Cut-off Date',
  SELECT_BILLING_DEADLINE: 'Select cut-off date',
} as const;

export const LeaderLabels = {
  TITLE: 'Staff Management',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  LEADER_ID: 'Manager ID',
  LEADER_NAME: 'Manager Name',
  PHONE: CommonLabels.PHONE_NUMBER,
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  STORE_NAME: 'Store Name',
  PASSWORD: CommonLabels.PASSWORD,
  LEADER_REGISTRATION: 'Register Staff Account',
  ENTER_LEADER_ID: 'Enter staff ID',
  ENTER_LEADER_NAME: 'Enter staff name',
  ENTER_PHONE: 'Enter phone number',
  ENTER_PASSWORD: CommonLabels.ENTER_PASSWORD,
  PLEASE_SELECT: CommonLabels.PLEASE_SELECT,
  SELECT_BRANCH: CommonLabels.PLEASE_SELECT_BRANCH,
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const ServiceLabels = {
  TITLE: 'Inventory Levels & Services',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  SERVICE_ID: 'Service ID',
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  PRICE: CommonLabels.PRICE,
  QUANTITY: CommonLabels.QUANTITY,
  SERVICE_REGISTRATION: 'Register Service',
  ENTER_SERVICE_NAME: 'Enter service name',
  ENTER_PRICE: 'Enter price amount',
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const OptionLabels = {
  TITLE: 'Suppliers & Product Options',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  OPTION_ID: 'Option ID',
  OPTION_NAME: CommonLabels.OPTION_NAME,
  PRICE: CommonLabels.PRICE,
  OPTION_TYPE: CommonLabels.OPTION_TYPE,
  OPTION_REGISTRATION: 'Register Option Item',
  ENTER_OPTION_NAME: 'Enter option name',
  ENTER_PRICE: 'Enter option price',
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const SetLabels = {
  TITLE: 'Product Sets & Bundles',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  SET_ID: CommonLabels.SET_ID,
  SET_NAME: CommonLabels.SET_NAME,
  SIZE: CommonLabels.SIZE,
  TYPE: CommonLabels.TYPE,
  SET_REGISTRATION: 'Register Product Bundle',
  ENTER_SET_NAME: 'Enter bundle set name',
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const SummaryListLabels = {
  TITLE: 'NK Fashions Sales Dashboard',
  BILL_CLOSING_TITLE: 'NK Fashions Audit Logs',
  SELECT: CommonLabels.SELECT,
  CSV_EXPORT: 'Export CSV',
  CSV_CONFIRM_MESSAGE: CommonLabels.CSV_CONFIRM_MESSAGE,
  JOB_IN_PROGRESS: CommonLabels.JOB_IN_PROGRESS,
  CSV_EXPORT_FAILED: 'Failed to generate CSV export file.',
  DELIVER_CONFIRM_MESSAGE: CommonLabels.DELIVER_CONFIRM_MESSAGE,
  NO_DELIVERY_CONFIRM_MESSAGE: CommonLabels.NO_DELIVERY_CONFIRM_MESSAGE,
  YES_TEXT: CommonLabels.YES_TEXT,
  NO_TEXT: CommonLabels.NO_TEXT,
  LOADING: CommonLabels.LOADING,
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  PLEASE_SELECT_KANJI: CommonLabels.PLEASE_SELECT_KANJI,
  ENTER_BRANCH_NAME: CommonLabels.ENTER_BRANCH_NAME,
  SELECT_HOSPITAL: CommonLabels.SELECT_HOSPITAL,
  PATIENT_NAME: CommonLabels.PATIENT_NAME,
  ENTER_PATIENT_NAME: CommonLabels.ENTER_PATIENT_NAME,
  SEARCH: 'Search',
  SERVICE_DAYS_TOTAL: 'Total Service Days',
  TOTAL_AMOUNT: 'Total Amount',
  TOTAL_OPTION_AMOUNT: 'Total Option Amount',
  GRAND_TOTAL_AMOUNT: 'Grand Total Amount',
  DATE: CommonLabels.DATE,
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  BRANCH: CommonLabels.BRANCH,
  USER_NAME: CommonLabels.PATIENT_NAME,
  BUILDING: CommonLabels.BUILDING,
  CATEGORY: CommonLabels.CATEGORY,
  ROOM: CommonLabels.ROOM,
  ROOM_NUMBER: CommonLabels.ROOM_NUMBER,
  ROUTE_NAME: CommonLabels.ROUTE_NAME,
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  PRICE: CommonLabels.PRICE,
  SERVICE_START_DATE: CommonLabels.SERVICE_START_DATE,
  SERVICE_END_DATE: CommonLabels.SERVICE_END_DATE,
  SERVICE_USAGE_DAYS: 'Usage Days',
  SERVICE_TOTAL_AMOUNT: 'Service Total',
  OPTION_NAME: CommonLabels.OPTION_NAME,
  OPTION_TYPE: CommonLabels.OPTION_TYPE,
  OPTION_START_DATE: CommonLabels.OPTION_START_DATE,
  OPTION_END_DATE: CommonLabels.OPTION_END_DATE,
  OPTION_USAGE_DAYS: 'Option Usage Days',
  OPTION_TOTAL_AMOUNT: 'Option Total',
  QUANTITY: CommonLabels.QUANTITY,
  OPTION_PRICE: CommonLabels.PRICE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const UserListLabels = {
  TITLE: 'Customer & Staff Accounts',
  STATUS_ALL: 'All',
  STATUS_ACTIVE: 'Active Accounts',
  STATUS_ENDED: 'Inactive Accounts',
  START_DATE_PLACEHOLDER: 'Filter Start Date',
  END_DATE_PLACEHOLDER: 'Filter End Date',
  BRANCH_PLACEHOLDER: 'Filter Store',
  HOSPITAL_PLACEHOLDER: 'Filter Catalog',
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  USER_NAME: CommonLabels.PATIENT_NAME,
  ADDRESS: CommonLabels.ADDRESS,
  PHONE: CommonLabels.PHONE_NUMBER,
  BUILDING_NAME: CommonLabels.BUILDING,
  FLOOR_NUMBER: CommonLabels.FLOOR_NUMBER,
  ROUTE_NAME: CommonLabels.ROUTE_NAME,
  ROOM_NUMBER: CommonLabels.ROOM_NUMBER,
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  SERVICE_START_DATE: CommonLabels.SERVICE_START_DATE,
  SERVICE_END_DATE: CommonLabels.SERVICE_END_DATE,
  OPTION_NAME: CommonLabels.OPTION_NAME_SALE_HALF,
  QUANTITY: CommonLabels.QUANTITY,
  SALE_DATE: CommonLabels.SALE_DATE,
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const UserNkStaffLabels = {
  TITLE: 'Employee Directory',
  STATUS_ALL: 'All',
  STATUS_ACTIVE: 'Active',
  STATUS_ENDED: 'Archived',
  START_DATE_PLACEHOLDER: 'Search Start Date',
  END_DATE_PLACEHOLDER: 'Search End Date',
  BRANCH_PLACEHOLDER: 'Store Name',
  HOSPITAL_PLACEHOLDER: 'Catalog Name',
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  USER_NAME: CommonLabels.PATIENT_NAME,
  ADDRESS: CommonLabels.ADDRESS,
  PHONE: CommonLabels.PHONE_NUMBER,
  BUILDING_NAME: CommonLabels.BUILDING,
  FLOOR_NUMBER: CommonLabels.FLOOR_NUMBER,
  ROUTE_NAME: CommonLabels.ROUTE_NAME,
  ROOM_NUMBER: CommonLabels.ROOM_NUMBER,
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  SERVICE_START_DATE: CommonLabels.SERVICE_START_DATE,
  SERVICE_END_DATE: CommonLabels.SERVICE_END_DATE,
  OPTION_NAME: CommonLabels.OPTION_NAME_SALE_HALF,
  QUANTITY: CommonLabels.QUANTITY,
  SALE_DATE: CommonLabels.SALE_DATE,
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const UserHospitalStaffLabels = {
  TITLE: 'Customer Account Registry',
  STATUS_ALL: 'All',
  STATUS_ACTIVE: 'Active',
  STATUS_ENDED: 'Closed',
  START_DATE_PLACEHOLDER: 'Search Start Date',
  END_DATE_PLACEHOLDER: 'Search End Date',
  BRANCH_PLACEHOLDER: 'Store Name',
  HOSPITAL_PLACEHOLDER: 'Product Group',
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  USER_NAME: 'Customer Name',
  ADDRESS: CommonLabels.ADDRESS,
  PHONE: CommonLabels.PHONE_NUMBER,
  CATEGORY: CommonLabels.CATEGORY,
  ROOM_NUMBER: CommonLabels.ROOM_NUMBER,
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  SERVICE_START_DATE: CommonLabels.SERVICE_START_DATE,
  SERVICE_END_DATE: CommonLabels.SERVICE_END_DATE,
  SUSPENSION_PERIOD: 'Hold Period',
  OPTION_NAME: CommonLabels.OPTION_NAME_SALE_HALF,
  SALE_DATE: CommonLabels.SALE_DATE,
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const LeaderUserNkStaffLabels = {
  TITLE: 'Store Staff Accounts',
  STATUS_ALL: 'All',
  STATUS_ACTIVE: 'Active',
  STATUS_ENDED: 'Inactive',
  USER_NAME_PLACEHOLDER: 'Staff Member Name',
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  USER_NAME: CommonLabels.PATIENT_NAME,
  ADDRESS: CommonLabels.ADDRESS,
  PHONE: CommonLabels.PHONE_NUMBER,
  BUILDING_NAME: CommonLabels.BUILDING,
  FLOOR_NUMBER: CommonLabels.FLOOR_NUMBER,
  ROUTE_NAME: CommonLabels.ROUTE_NAME,
  ROOM_NUMBER: CommonLabels.ROOM_NUMBER,
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  SERVICE_START_DATE: CommonLabels.SERVICE_START_DATE,
  SERVICE_END_DATE: CommonLabels.SERVICE_END_DATE,
  OPTION_NAME: CommonLabels.OPTION_NAME_SALE_HALF,
  QUANTITY: CommonLabels.QUANTITY,
  SALE_DATE: CommonLabels.SALE_DATE,
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const LeaderUserHospitalStaffLabels = {
  TITLE: 'Store Customer Registry',
  STATUS_ALL: 'All',
  STATUS_ACTIVE: 'Active Clients',
  STATUS_ENDED: 'Archived Clients',
  USER_NAME_PLACEHOLDER: 'Client Name',
  HOSPITAL_NAME: CommonLabels.HOSPITAL_NAME,
  USER_NAME: CommonLabels.PATIENT_NAME,
  ADDRESS: CommonLabels.ADDRESS,
  PHONE: CommonLabels.PHONE_NUMBER,
  CATEGORY: CommonLabels.CATEGORY,
  ROOM_NUMBER: CommonLabels.ROOM_NUMBER,
  SERVICE_NAME: CommonLabels.SERVICE_NAME,
  SERVICE_START_DATE: CommonLabels.SERVICE_START_DATE,
  SERVICE_END_DATE: CommonLabels.SERVICE_END_DATE,
  SUSPENSION_PERIOD: 'Hold Period',
  OPTION_NAME: CommonLabels.OPTION_NAME_SALE_HALF,
  QUANTITY: CommonLabels.QUANTITY,
  SALE_DATE: CommonLabels.SALE_DATE,
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const HospitalStaffClassificationListLabels = {
  TITLE: 'Categories & Classifications',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  CLASSIFICATION_NAME: 'Classification Name',
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const ClassificationListLabels = {
  TITLE: 'Catalog Categories',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  CLASSIFICATION_NAME: 'Classification Name',
  UPDATE: CommonLabels.UPDATE,
  SAVE: CommonLabels.SAVE,
  NO_DATA: CommonLabels.NO_DATA,
} as const;

export const DeliveryRequestLabels = {
  TITLE: 'POS Cashier Register',
  TODAY: 'Today',
  TOMORROW: 'Tomorrow',
  DAY_AFTER_TOMORROW: 'Day After Tomorrow',
  PAST_MISSED: 'Held / Delayed',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  DELIVERY_STATUS: 'Status',
  DELIVERY_STATUS_DELIVERED: 'Completed',
  DELIVERY_STATUS_NOT_DELIVERED: 'Pending',
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const InvoiceConfirmationListLabels = {
  TITLE: 'Invoice Confirmation',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  CONFIRMED: 'Confirmed',
  UNCONFIRMED: 'Unconfirmed',
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const AfterDeliveryLabels = {
  TITLE: 'Order Fulfillment History',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  ADD: CommonLabels.ADD,
  STATUS: 'Status',
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const CompletedDistributionListLabels = {
  TITLE: 'Completed Order Deliveries',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  DATE: CommonLabels.DATE,
  STATUS: 'Completed',
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const IncompleteDistributionListLabels = {
  TITLE: 'Pending Order Deliveries',
  SEARCH_PLACEHOLDER: CommonLabels.SEARCH_PLACEHOLDER,
  DATE: CommonLabels.DATE,
  STATUS: 'Pending',
  EMPTY: CommonLabels.NO_DATA,
} as const;

export const LoginLabels = {
  LOGIN: 'LOGIN',
  LOGIN_IMAGE_ALT: CommonLabels.LOGIN_IMAGE_ALT,
  USER_ID: 'User Email / ID',
  ENTER_USER_ID: 'Please enter your ID or Email',
  BRANCH_ID: 'Store Location ID',
  BRANCH_CODE: 'Store Code',
  ENTER_BRANCH_CODE: 'Please enter Store Code',
  PLEASE_SELECT_BRANCH: 'Please select a Store Location',
  HOSPITAL_ID: 'Loyalty ID',
  HOSPITAL_CODE: 'Customer ID',
  ENTER_HOSPITAL_CODE: 'Please enter Customer ID',
  ENTER_HOSPITAL_ID: 'Please enter Customer Loyalty ID',
  PASSWORD: 'Password / PIN',
  ENTER_PASSWORD: 'Please enter your Password or PIN',
  HOMEPAGE: 'Homepage',
  NEXT: 'Next',
  ROLE_TEXT_ADMIN: 'System Admin',
  ROLE_TEXT_LEADER: 'Store Manager',
  ROLE_TEXT_STAFF: 'POS Cashier',
  ROLE_TEXT_HOSPITAL_STAFF: 'Customer Portal',
} as const;

export const StaffLoginLabels = {
  LOGIN_IMAGE_ALT: CommonLabels.LOGIN_IMAGE_ALT,
  LOGIN: CommonLabels.LOGIN,
  STAFF: 'POS Cashier',
  BRANCH_NAME: CommonLabels.BRANCH_NAME,
  PLEASE_SELECT_BRANCH: CommonLabels.PLEASE_SELECT_BRANCH,
  LEADER_NAME: 'Store Manager',
  PLEASE_SELECT_LEADER: 'Select store manager',
  HOSPITAL_NAME: 'Store Name',
  PLEASE_SELECT_HOSPITAL: 'Select store counter',
  PASSWORD: CommonLabels.PASSWORD,
} as const;

export const HospitalStaffLoginLabels = {
  LOGIN_IMAGE_ALT: CommonLabels.LOGIN_IMAGE_ALT,
  LOGIN: CommonLabels.LOGIN,
  HOSPITAL_STAFF: 'Customer Account',
  BRANCH_CODE: CommonLabels.BRANCH_CODE,
  ENTER_BRANCH_CODE: CommonLabels.ENTER_BRANCH_CODE,
  HOSPITAL_CODE: CommonLabels.HOSPITAL_CODE,
  ENTER_HOSPITAL_CODE: CommonLabels.ENTER_HOSPITAL_CODE,
  PASSWORD: CommonLabels.PASSWORD,
  ENTER_PASSWORD: CommonLabels.ENTER_PASSWORD,
  HOMEPAGE: 'Homepage',
  NEXT: 'Next',
} as const;

export const LandingLabels = {
  COMPANY_TITLE: 'NK Fashions Retail Boutique',
  HEAD_OFFICE_LOGIN_ALT: 'System Admin Portal',
  HEAD_OFFICE_LOGIN: 'Admin Control Room',
  LEADER_LOGIN_ALT: 'Store Manager Portal',
  LEADER_LOGIN: 'Store Manager Portal',
  STAFF_LOGIN_ALT: 'POS Cashier Login',
  STAFF_LOGIN: 'POS Cashier Terminal',
  HOSPITAL_STAFF_LOGIN_ALT: 'Customer Account Portal',
  HOSPITAL_STAFF_LOGIN: 'Customer Account Portal',
} as const;

export const SidebarLabels = {
  TOP: 'Sales Dashboard',
  BRANCH_LIST: 'Stores & Warehouses',
  HOSPITAL_LIST: 'Products Catalog',
  LEADER_LIST: 'Staff Management',
  SERVICE_LIST: 'Inventory Levels',
  OPTION_LIST: 'Suppliers & POs',
  USER_LIST: 'Employee Accounts',
  NK_STAFF: 'Central Staff',
  HOSPITAL_STAFF: 'Store Cashiers',
  NK_COMPLETED_DISTRIBUTION_LIST: 'Completed Transfers',
  NK_INCOMPLETE_DISTRIBUTION_LIST: 'Pending Transfers',
  DELIVERY_REQUEST_LIST: 'Cashier Terminal',
  COMPLETED_DISTRIBUTION_LIST: 'Sales History',
  INCOMPLETE_DISTRIBUTION_LIST: 'Held Checkouts',
  AFTER_DELIVERY_LIST: 'My Orders',
  HOSPITAL_MASTER: 'Address Book',
  OPTION_MASTER: 'Wishlist',
  INVOICE_CONFIRMATION_LIST: 'Wishlist Items',
  BILL_CLOSING: 'Audit Logs',
} as const;

export const ToasterMessages: Record<string, string> = {
  updateSuccess: 'Updated successfully.',
  registerSuccess: 'Saved and registered successfully.',
  updateFailed: 'Failed to update record.',
  registerFailed: 'Failed to save record.',
  deleteSuccess: 'Deleted record successfully.',
  deleteFailed: 'Failed to delete record.',
  fetchFailed: 'Failed to retrieve data.',
  loginFailed: 'Invalid credentials. Please check your username and password.',
  logoutSuccess: 'Logged out successfully.',
  csvSuccess: 'CSV file generated successfully.',
  csvFailed: 'Failed to export CSV file.',
} as const;
