/* eslint-disable no-restricted-imports */
import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

/**
 * Interface representing OpenAPI structure
 */
interface OpenAPI {
  paths?: Record<string, any>;
  components?: { schemas?: Record<string, any> };
}

// Directories
const modelsDir = path.join(__dirname, 'src', 'app', 'models');
const apiModelDir = path.join(__dirname, 'src', 'app', 'api', 'model');

// Ensure models folder exists and is empty
if (fs.existsSync(modelsDir)) {
  fs.readdirSync(modelsDir).forEach((file) =>
    fs.unlinkSync(path.join(modelsDir, file)),
  );
} else {
  fs.mkdirSync(modelsDir, { recursive: true });
}

function toCamelCase(str: string) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function toPascalCase(str: string) {
  return str
    .split(/[_\s-]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Recursively append TS file content based on $ref and imports inside src/app/api/model
 */
function appendRefFile(
  schemaName: string,
  appended = new Set<string>(),
): string {
  const camelFileName = toCamelCase(schemaName) + '.ts';
  const filePath = path.join(apiModelDir, camelFileName);

  if (!fs.existsSync(filePath)) {
    console.warn(`Source file not found: ${filePath}`);
    return '';
  }

  if (appended.has(schemaName)) {
    return ''; // already appended
  }
  appended.add(schemaName);

  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  let content = '';
  let inHeader = true;

  for (const line of lines) {
    const trimmed = line.trim();
    // 1. Detect end of header comment block (typically starts with /** and ends with */)
    if (inHeader) {
      if (trimmed.endsWith('*/')) {
        inHeader = false;
      }
      continue;
    }

    // 2. Filter out ALL import statements
    if (trimmed.startsWith('import ')) {
      continue;
    }

    // 3. Keep everything else
    content += line + '\n';
  }

  // 🔹 Resolve imports
  const importRegex = /import\s+{[^}]+}\s+from\s+['"]\.\/(.+)['"]/g;
  let importMatch;
  while ((importMatch = importRegex.exec(lines.join('\n'))) !== null) {
    const importFile = importMatch[1] + '.ts';
    const importPath = path.join(apiModelDir, importFile);
    if (fs.existsSync(importPath)) {
      const importedSchema = toPascalCase(path.basename(importFile, '.ts'));
      content += appendRefFile(importedSchema, appended);
    }
  }

  // 🔹 Resolve $ref inside content
  const refRegex = /\$ref:\s*['"]#\/components\/schemas\/([A-Za-z0-9_]+)['"]/g;
  let refMatch;
  while ((refMatch = refRegex.exec(content)) !== null) {
    const innerRef = refMatch[1];
    content += appendRefFile(innerRef, appended);
  }

  return content;
}

try {
  const fileContents = fs.readFileSync('rest_api.yml', 'utf8');
  const data = yaml.load(fileContents) as OpenAPI;

  if (!data.paths) {
    console.log('No paths found in YAML');
    process.exit(0);
  }

  const pathGroups: Record<string, string[]> = {};
  Object.keys(data.paths).forEach((apiPath) => {
    if (apiPath.includes('{proxy+}')) return;

    const parts = apiPath.split('/').filter(Boolean);
    if (parts.length === 0) return;

    const topLevel = parts[0];
    if (!pathGroups[topLevel]) pathGroups[topLevel] = [];
    pathGroups[topLevel].push(apiPath);
  });

  for (const topLevel of Object.keys(pathGroups)) {
    const modelFilePath = path.join(modelsDir, `${topLevel}.model.ts`);
    let content = `/**
 * Koyama Shokai API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
\n\n`;

    for (const apiPath of pathGroups[topLevel]) {
      const pathItem = data.paths![apiPath];
      if (!pathItem) continue;

      for (const method of Object.keys(pathItem)) {
        const methodDef = pathItem[method];
        if (!methodDef) continue;

        // 🔹 Handle requestBody $ref
        const requestBodyRef =
          methodDef.requestBody?.content?.['application/json']?.schema?.$ref;
        if (requestBodyRef) {
          const schemaName = requestBodyRef.split('/').pop()!;
          const appendedContent = appendRefFile(schemaName);
          if (appendedContent) {
            content += '\n' + appendedContent;
          }
        }

        const responses: Record<string, any> = methodDef.responses || {};

        for (const status of Object.keys(responses)) {
          const response: any = responses[status];

          if (!response?.content?.['application/json']?.schema) continue;

          const schema = response.content['application/json'].schema;

          if (status === '200' && schema.$ref) {
            // Existing behavior: append normal response
            const schemaName = schema.$ref.split('/').pop()!;
            let appendedContent = appendRefFile(schemaName);
            if (appendedContent) {
              appendedContent = removeNamespaceBlocks(appendedContent);
              appendedContent = appendedContent.replace(
                /status_code:\s*[^;]+;/g,
                `status_code: 200;`,
              );
              appendedContent = appendedContent.replace(
                /result:\s*[^;]+;/g,
                `result: 'OK';`,
              );
              content += '\n' + appendedContent;
            }
          } else if (status !== '200') {
            // Non-200 responses -> generate error interface
            const errorInterfaceName = `ErrorMessage${status}`;
            const errorInterface = generateInterfaceFromSchema(
              schema,
              errorInterfaceName,
            );
            if (errorInterface) {
              content += '\n' + errorInterface;
            }
          }
        }
      }
    }

    content = removeDuplicateInterfaces(content);
    fs.writeFileSync(modelFilePath, content);
    console.log(`Created model: ${modelFilePath}`);
  }

  // ✅ Final cleanup
  const apiFolder = path.resolve(__dirname, 'src/app/api');
  fs.rmSync(apiFolder, { recursive: true, force: true });
  console.log(`✅ Cleaned up ${apiFolder}`);
} catch (e) {
  console.error('Error reading YAML:', e);
}

/**
 * Removes all TypeScript `export namespace` blocks from the given content.
 *
 * This function handles multi-line namespaces and nested braces correctly.
 * It is useful when copying generated interfaces and you want to eliminate
 * any namespace declarations including inner enums or types.
 *
 * @param content - The string content of a TypeScript file to process.
 * @returns The content with all `export namespace ... { ... }` blocks removed.
 *
 * @example
 * const input = `
 * export namespace VehicleResponse {
 *   export const StatusCodeEnum = { NUMBER_200: 200 } as const;
 *   export type StatusCodeEnum = typeof StatusCodeEnum[keyof typeof StatusCodeEnum];
 * }
 * export interface VehicleUpdateResponse { status_code: number; }
 * `;
 *
 * const output = removeNamespaceBlocks(input);
 * // output:
 * // export interface VehicleUpdateResponse { status_code: number; }
 */
function removeNamespaceBlocks(content: string): string {
  const lines = content.split(/\r?\n/);
  const result: string[] = [];
  let skip = false;
  let braceCount = 0;

  for (const line of lines) {
    if (!skip && line.match(/export\s+namespace\s+\w+\s*\{/)) {
      // Start skipping lines inside the namespace
      skip = true;
      braceCount =
        (line.match(/{/g) || []).length - (line.match(/}/g) || []).length;
      continue;
    }
    if (skip) {
      // Adjust brace count for nested braces
      braceCount += (line.match(/{/g) || []).length;
      braceCount -= (line.match(/}/g) || []).length;
      if (braceCount <= 0) {
        // End of namespace block
        skip = false;
      }
      continue;
    }
    // Keep lines outside namespace
    result.push(line);
  }

  return result.join('\n');
}

/**
 * Removes duplicate TypeScript interfaces from the content.
 *
 * @param content - The string content of a TypeScript file.
 * @returns The content with only unique `export interface` blocks (duplicates removed).
 */
function removeDuplicateInterfaces(content: string): string {
  const interfaceRegex = /export\s+interface\s+(\w+)\s*{[^}]*}/gs;
  const seen = new Set<string>();
  let result = '';
  let lastIndex = 0;

  let match;
  while ((match = interfaceRegex.exec(content)) !== null) {
    const [fullMatch, interfaceName] = match;

    if (!seen.has(interfaceName)) {
      seen.add(interfaceName);
      result += content.slice(lastIndex, match.index) + fullMatch + '\n';
    }
    lastIndex = match.index + fullMatch.length;
  }
  // Append any remaining content after the last match
  result += content.slice(lastIndex);
  return result;
}

/**
 * Generates TypeScript interface from a JSON schema object
 *
 * @param schema - JSON schema object
 * @param name - Name of the interface
 * @returns TypeScript interface string
 */
function generateInterfaceFromSchema(schema: any, name: string): string {
  if (!schema || schema.type !== 'object' || !schema.properties) return '';

  const lines: string[] = [`export interface ${name} {`];

  for (const [propName, propDef] of Object.entries(schema.properties)) {
    const type = mapJsonSchemaTypeToTS(propDef);
    const description = (propDef as any).description;
    if (description) {
      lines.push(`  /** ${description} */`);
    }
    lines.push(`  ${propName}: ${type};`);
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

/**
 * Maps JSON Schema types to TypeScript types
 */
function mapJsonSchemaTypeToTS(propDef: any): string {
  if (propDef.$ref) {
    return propDef.$ref.split('/').pop()!;
  }

  switch (propDef.type) {
    case 'string':
      return `'${propDef.enum?.[0] ?? 'string'}'`;
    case 'integer':
    case 'number':
      return propDef.enum?.[0]?.toString() ?? 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      const itemType = propDef.items?.$ref
        ? propDef.items.$ref.split('/').pop()
        : (propDef.items?.type ?? 'any');
      return `${itemType}[]`;
    case 'object':
      return '{ [key: string]: any }';
    default:
      return 'any';
  }
}
